[project]
name = "iree-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "iree-base-compiler>=3.9.0",
    "iree-base-runtime>=3.9.0",
]
